name: forgejo
services:
  forgejo:
    container_name: forgejo
    deploy:
        resources:
          reservations:
            memory: "2147483648"
          limits:
            memory: 12887M
    image: forgejo/forgejo:9.0.3
    labels:
      icon: https://seeklogo.com/images/F/forgejo-logo-34620A5CD1-seeklogo.com.png
    ports:
      - target: 3000
        published: "3004"
        protocol: tcp
      - target: 22
        published: "224"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/forgejo/data
        target: /data
    x-casaos:
      envs:
        - container: USER_UID
          description:
            en_us: The UID (Unix user ID) of the user that runs Forgejo
            zh_cn: Forgejo 运行的用户的 UID（Unix 用户 ID）
        - container: USER_GID
          description:
            en_us: The GID (Unix group ID) of the user that runs Forgejo
            zh_cn: Forgejo 运行的用户的 GID（Unix 组 ID）
      ports:
        - container: "3000"
          description:
            en_us: WebUI Port
            zh_cn: WebUI 端口
        - container: "22"
          description:
            en_us: SSH Port
            zh_cn: SSH 端口
      volumes:
        - container: /data
          description:
            en_us: Forgejo data directory.
            zh_cn: Forgejo 数据目录。
    devices: []
    cap_add: []
    command: []
    network_mode: bridge
    privileged: false
    hostname: forgejo
    cpu_shares: 90
x-casaos:
  architectures:
    - amd64
    - arm64
  author: Raymond
  category: Developer
  description:
    en_us: Beyond coding. We forge. https://forgejo.org/ Forgejo is a self-hosted lightweight software forge.Easy to install and low maintenance, it just does the job. 
  developer: Forgejo
  icon: https://seeklogo.com/images/F/forgejo-logo-34620A5CD1-seeklogo.com.png
  index: /
  is_uncontrolled: false
  main: forgejo
  port_map: "3002"
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/screenshot-3.png
  store_app_id: forgejo
  tagline:
    ar_sa: Git مع كوب من الشاي
    de_de: Git mit einem Tässchen Tee
    en_us: Self-hosted software development service
    es_es: Git con una taza de té
    fr_fr: Git avec une tasse de thé
    hu_hu: Git egy csésze tea kíséretében
    it_it: Git con una tazza di tè
    pl_pl: Git z filiżanką herbaty
    pt_br: Git com uma xícara de chá
    ru_ru: Git с чашечкой чая
    sv_se: Git med en kopp te
    uk_ua: Git з чашкою чаю
    zh_cn: 自托管软件开发服务
  thumbnail: https://seeklogo.com/images/F/forgejo-logo-34620A5CD1-seeklogo.com.png
  tips:
    before_install:
      en_us: >
        When the App is installed, the first account registered will become the
        administrator account.
      zh_cn: |
        安装应用后，注册的第一个账号将成为管理员账号。
  title:
    en_us: Forgejo
    custom: ""
  hostname: ""
  scheme: http
